### ISSUE TITLE
Update Material Syntax to match Material syntax for Sublime Text

### ISSUE THREAD

**Issue by Gunny123** [atom-material/atom-material-syntax#40]
The syntax color scheme on Sublime was recently updated. Was just wondering if you were going to update to match potentially?

**Comment by haveanicedavid** [comment]
The current theme looks great, but Id love this as well

**Comment by Gunny123** [comment]
@silvestreh Any update on this?

**Comment by silvestreh** [comment]
I'll get to this as soon as I get some free time. It'll come, don't worry 😄

**Comment by Gunny123** [comment]
I could probably do it and then submit a pull request

**Comment by silvestreh** [comment]
That'd be great. All help is appreciated!

**Comment by Gunny123** [comment]
I haven't exactly ported a theme before. What would you recommend doing?

**Comment by silvestreh** [comment]
If changes are minimal, I would open Sublime and Atom side by side and update `amu-extra.less` to adjust things. Otherwise, you can use APM to convert TextMate Themes (the format Sublime uses). Either way you'll have to make extra adjustments in `amu-extra.less` because APM always makes mistakes and doesn't look the same.

**Comment by Gunny123** [comment]
```
// These colors are specific to the theme. Do not use in a package!

@very-light-gray: #c5c8c6;
@light-gray: #969896;
@gray: #373b41;
@dark-gray: #282a2e;
@very-dark-gray: #1d1f21;

@cyan: #8abeb7;
@blue: #81a2be;
@purple: #b294bb;
@green: #b5bd68;
@red: #cc6666;
@orange: #de935f;
@light-orange: #f0c674;
```

I did a quick direct conversion of the material color scheme using `apm` it gave me this file for the colors.

I guess I can find the counterparts in the Atom version and change them to match

**Comment by Announcement** [comment]
is this not the same as #44 ?

**Comment by tunnckoCore** [comment]
@equinusocio can you help?

**Comment by Gunny123** [comment]
@tunnckoCore @equinusocio I actually deleted this folder since I didn't have space in my Dropbox

**Comment by tunnckoCore** [comment]
> I actually deleted the folder

no matter :laughing: :)

**Comment by Gunny123** [comment]
I don't think this ever got worked on by anyone besides me. I think I can retrace my steps pretty quickly.

**Comment by equinusocio** [comment]
@Gunny123 I just made the Palenight version. Just copy the folder inside your atom packages directory.
[mt-palenight.zip](https://github.com/atom-material/atom-material-syntax/files/706498/mt-palenight.zip)

**Comment by tunnckoCore** [comment]
I did exactly this with few themes, but it seems to not work -- it is looks like just white plain text file.

**Comment by tunnckoCore** [comment]
@equinusocio how exactly you converted it? You this way still not works for me. I tried to convert palenight using that and looking at the less style files there are differences. And the theme not looks working.

![2017-01-15-20 27 13_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/21965061/a8f64c2c-db60-11e6-9e72-d42577aeaac8.png)
![2017-01-15-20 27 41_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/21965064/b9a866ea-db60-11e6-90e4-f9779bea5344.png)

Can you convert them all and push them somewhere?
Or at least the original default `Material-Theme.tmTheme`

**Comment by Gunny123** [comment]
@silvestreh @equinusocio Should #51 and #50 be merged into this issue for general housekeeping?

**Comment by equinusocio** [comment]
I'm not a contributor..

**Comment by octoxan** [comment]
The updated atom-material-syntax looks like garbage. Why the need for so many drastic changes?

**Comment by tunnckoCore** [comment]
@equinusocio could you just please convert the default theme? :) So I can try it.

**Comment by tunnckoCore** [comment]
@octoxan why garbage? In the screen shot it looks it is more better than previous and is more matching to the original Sublime theme.

@silvestreh is there any specific reason that it requires Atom >=1.13?

**Comment by tunnckoCore** [comment]
@silvestreh awesome! it now looks perfect :) Finally! Thanks a lot.

I think we can close this? :)

**Comment by octoxan** [comment]
@tunnckoCore It became the #1 rated syntax highlighting theme for Atom while looking like it did, and it now no longer looks anything like before.

A lot of stuff for Blade syntax highlighting now looks broken.

Most of my php/blades files are now 50% white and 40% purple. 

And look at SASS files for example...

Before:
![good](https://cloud.githubusercontent.com/assets/4382195/22068772/16349b36-dd64-11e6-8534-39ce59a4c254.png)

After:
![horrible](https://cloud.githubusercontent.com/assets/4382195/22068760/0aefb440-dd64-11e6-8d86-ed6ececd05ea.png)

In the before you could much more easily scan and see things like units of measurements vs actual measurements, or 'solid' and 'bold' seem to actually stand out. In the after... everything after the colon is just a different shade of red/orange.

I'm not sure why you'd want to take the highest rated syntax theme and completely change it. It was popular _for a reason_.

Oh well, do what you guys want. The joy of git is I'm forking an old version. =]

**Comment by tunnckoCore** [comment]
I'm not talking anything about that. The javascript syntax of 1.0.1 now looks more better than the 0.4.6, that's what I'm talking and thanking :) But yea you're right for the SASS example.

**Comment by silvestreh** [comment]
@octoxan What happened is that this theme used to be a direct (and automatic) conversion of the Sublime version. Many complaints, like yours, raised after the latest conversion so I decided to ditch the automatization part and start doing it by hand.

You're very much free to fork, but I would _really appreciate_ some feedback on what's bothering you the most (the Sass examples you provided are pure gold and I absolutely agree with you there)

I'll be fixing these things and going back closer to what the old version looked like.

**Comment by octoxan** [comment]
@silvestreh 

Awesome! I'll dig into it some more when I'm off work and try to point out more things or help fix things like that.

**Comment by silvestreh** [comment]
@octoxan Just pushed a new patch with some tweaks for CSS-like languages

<img width="424" alt="captura de pantalla 2017-01-18 a las 2 30 41 p m" src="https://cloud.githubusercontent.com/assets/1133339/22075438/c26524b8-dd8a-11e6-850f-40df7df736d1.png">

**Comment by equinusocio** [comment]
Do you really think taht the units are more importants than the value? Now you first recognize the unit before the value.

**Comment by octoxan** [comment]
@equinusocio Why would this change make you recognize the unit before the value? 

Now they're different enough again to where your mind should be able to scan and know which color to look for depending on the what you're looking for. The old new way had them practically blend together.

**Comment by silvestreh** [comment]
@equinusocio I *think* see what you mean (if contrast between back and foreground is what you're talking about.)

I'm sure it wouldn't pass the WCAG 2 AAA accessibility test, but neither would Sublime's version because it's all red… and I do enjoy differentiating between unit and value.

I'll probably reverse it because you do make a point that units stand out more than value. Something like…

<img width="434" alt="captura de pantalla 2017-01-18 a las 3 23 00 p m" src="https://cloud.githubusercontent.com/assets/1133339/22077219/1045e21a-dd92-11e6-9a8a-f8b0fdc7fa78.png">

**Comment by equinusocio** [comment]
The original Material Theme color scheme for css is this one:
<img width="284" alt="screen shot 2017-01-19 at 09 50 52" src="https://cloud.githubusercontent.com/assets/10454741/22099752/e88e6ac6-de2c-11e6-8f3a-2145e2afb5b7.png">

**Comment by silvestreh** [comment]
@equinusocio this is no longer a direct port of the sublime theme… I've decided to diverge from it a little bit 😄

**Comment by equinusocio** [comment]
My comment is for @Gunny123 that open the original issue about a 1:1 conversion. You should close this issue because this, as you pointed out, is not more the official scheme porting. :)
