### ISSUE TITLE
Keep updating with sublime text version?

### ISSUE THREAD

**Issue by lednhatkhanh** [atom-material/atom-material-syntax#44]
This project stopped updating for while, but the sublime is still being updated.

**Comment by silvestreh** [comment]
Thanks! I'm closing this 'cause it's a dupe of #40 … This project is, for the most part, a one-man-show and I'm a little short on my free time. I'll get to it eventually 😄 . You're more than welcomed to contribute if you really can't wait, I'd really appreciate an extra pair of hands.
