### ISSUE TITLE
Background Colour Change on Selection

### ISSUE THREAD

**Issue by elebumm** [atom-material/atom-material-syntax#49]
Hi,

I love the colours and the design for atom-material-syntax and ui. You have done an amazing job.

I am having a little issue with the syntax part of this. I want the whole background to be one colour but it changes depending on what's selected. Here is an example:

[What it looks like.](http://imgur.com/71B5rM6/)

I have tried to change the syntax in case and the rest work fine. Any ideas as to whats causing this problem?

**Comment by silvestreh** [comment]
This, I believe, is not an issue with either material-ui or material-syntax, but with Electron itself. You can read more about it on [atom/atom#12634](https://github.com/atom/atom/issues/12634).

Let me know if the workarounds mentioned in that issue work for you so I can close this issue 😄

**Comment by elebumm** [comment]
Thanks @silvestreh for the quick reply. I checked out the issue and found that by opening up my terminal and running `atom --disable-gpu' it solved my problem.
