### ISSUE TITLE
Just updated to .4.8, is the Python highlighting supposed to look this bad?

### ISSUE THREAD

**Issue by tristan957** [atom-material/atom-material-syntax#50]
It did not look this bad before the update. It was my favorite syntax theme before the update. 
![materialsyntax](https://cloud.githubusercontent.com/assets/11936772/21908371/19f2cb7e-d8d9-11e6-85f7-daa40d831f08.png)

**Comment by silvestreh** [comment]
To be completely honest: _probably_. This theme is just an automatic conversion of the Sublime Text version with a few added things, like the matching bracket highlight.

**Comment by JosephMart** [comment]
:(

**Comment by tristan957** [comment]
Well that's unfortunate. Maybe I'll give it a chance :/

**Comment by silvestreh** [comment]
let me know which are the biggest issues with the current look and I'll try my best to fix them. For example: I myself, am not digging the italic keywords.

**Comment by tristan957** [comment]
Yes, the italic keywords are being largely overused in my opinion. Also for instance a line like line 21 in my screenshot, there seems to be way too much orange. Generally the previous iteration of this theme was really good. Line 34 in the screenshot, it would be nice if there wasn't so much of the same blue everywhere. I think the red for "self" could be a different red. It just seems to pop out way too much through all that blue. I'm a fan of the colors but I think a couple could be added for more variety.

It's just weird to me that the syntax highlighting could change so dramatically like that. Thanks for being active in your theme though. Most syntax themes are old with the latest revisions being over 2 years ago. That's why I liked yours a lot. Hopefully you share a lot of the same sentiments about this.

**Comment by moxaj** [comment]
@tristan957 +1 (italics, overused blue shade)

**Comment by silvestreh** [comment]
@tristan957 (and everyone else for that matter) I'm mixing the old with the new… Here's what it looks like:

![captura de pantalla 2017-01-16 a las 12 53 25 p m](https://cloud.githubusercontent.com/assets/1133339/21989720/cfff007c-dbea-11e6-84c5-a98d6c30298f.png)

I know jack about Python, so ignore the snippets 😁

**Comment by tristan957** [comment]
This looks really good. When can we expect an update?

**Comment by silvestreh** [comment]
As soon as I go through other popular languages, like PHP. I'm making separate stylesheets for language-specific tweaks 😄

**Comment by silvestreh** [comment]
While still somewhat different, version 1.0.0 (which is a complete rewrite) provides a mix between the old and the updated look.

**Comment by tristan957** [comment]
I didn't notice before but I love how you used some of my code for your example in the previous screenshot

**Comment by silvestreh** [comment]
heh, yeah, so you could compare with (part of) the same snippet 😄

**Comment by tristan957** [comment]
Hey. I just updated. I feel like one of the blue colors is still really overused. It happens mainly when you have a variable name with a function/method.

`self.variable.function()`. The variable and function are the same blue. Is there anyway to get the variable to possibly be white so I'm not looking at a rainbow haha :)

**Comment by silvestreh** [comment]
Well, it's in line with the original theme. The highlighting "engine" doesn't differentiate between the parts:

```html
<span class="syntax--meta syntax--function-call syntax--python">
    <span class="syntax--variable syntax--language syntax--self syntax--python">self</span>
    .variable.function
    <span class="syntax--punctuation syntax--definition syntax--arguments syntax--begin syntax--python">(</span>
    <span class="syntax--meta syntax--function-call syntax--arguments syntax--python">argument</span>
    <span class="syntax--punctuation syntax--definition syntax--arguments syntax--end syntax--python">)</span>
</span>
```

As you can appreciate, the string `.variable.function` is styled the same, not because I choose to, but because I can't do it different.

**Comment by tristan957** [comment]
Unlucky oh well thanks for the heads up
