### ISSUE TITLE
Selected text is not very visible

### ISSUE THREAD

**Issue by bernardop** [atom-material/atom-material-syntax#54]
When selecting text, the highlight can be easily lost with the background. Could a different color or lighter shade of gray be used? In the following screenshot, the text `isCustomerLoggedInEpic` is selected.
![screen shot 2017-01-17 at 11 59 45 am](https://cloud.githubusercontent.com/assets/28455/22030793/ccf96f94-dcac-11e6-8cf9-0f5ba5d55797.png)

**Comment by silvestreh** [comment]
I recently wrote the theme by hand instead of doing the usual automatic conversion from Sublime's theme… with that said, I'll take a look!

Thanks!

**Comment by bernardop** [comment]
I love this theme, thanks for the quick fix!
