### ISSUE TITLE
In platformio pop ups do not appear correctly

### ISSUE THREAD

**Issue by jordipc** [atom-material/atom-material-syntax#64]
The input fields in popup messages are very big and it can't see completely.
Please excuse my limited English. Corrections are welcome.
![platformio](https://cloud.githubusercontent.com/assets/3213913/25818714/da903d46-342b-11e7-92ce-02a92d599f5a.png)

**Comment by silvestreh** [comment]
are you using Material UI `1.3.10`?

**Comment by jordipc** [comment]
Yes I'm using Material UI ```1.3.10``` and Material syntax ```1.0.3``` 
Thanks!

**Comment by silvestreh** [comment]
Looks like this is an issue with the UI package, not the syntax. In any case, there's a new version for the UI theme, `2.0`, but it requires Atom 1.17 which is currently on beta. If you're willing to upgrade to a beta release make sure to give Material UI 2.0 a try!

**Comment by jordipc** [comment]
Hi @silvestreh , on Atom 1.17 works perfectly.
Thank you very much!

**Comment by silvestreh** [comment]
Cool! Thanks for letting me know 👍
