### ISSUE TITLE
CSS properties have the same color as class selectors with 1.0.3 release

### ISSUE THREAD

**Issue by eramdam** [atom-material/atom-material-syntax#65]
![image](https://cloud.githubusercontent.com/assets/1409924/25819901/4efd4270-33e4-11e7-9911-b7375e1d44b9.png)

See in comparison the dark variant of this syntax theme (I don't have an old version of the non-dark one anymore though...)
![image](https://cloud.githubusercontent.com/assets/1409924/25819933/65ecf408-33e4-11e7-8eb2-804d761a6c8f.png)

**Comment by silvestreh** [comment]
is this regular CSS, Sass, LESS?

**Comment by eramdam** [comment]
@silvestreh regular CSS. I'm on Atom 1.17.0-beta4 FWIW

**Comment by silvestreh** [comment]
Ah! It looks like something in Atom 1.17 is making them like this.

Here's on Atom 1.16
<img width="327" alt="captura de pantalla 2017-05-08 a la s 16 06 45" src="https://cloud.githubusercontent.com/assets/1133339/25820640/626a7598-3408-11e7-9cbe-03fc7185a01c.png">


And here's on 1.17
<img width="337" alt="captura de pantalla 2017-05-08 a la s 16 06 53" src="https://cloud.githubusercontent.com/assets/1133339/25820647/65d5b8c8-3408-11e7-8aec-d0ea5ba92578.png">

**Comment by eramdam** [comment]
You can check 1.17's changelog, I don't see anything that should change that but I may be missing something! https://github.com/atom/atom/releases

**Comment by silvestreh** [comment]
well, they upgraded LESS, that could be doing something…

**Comment by silvestreh** [comment]
aaaaaand… fixed!
