### ISSUE TITLE
About font

### ISSUE THREAD

**Issue by DonadoJuan** [atom-material/atom-material-syntax#72]
I was wondering what font are you using in the image example?
it match up with syntax really well
thanks for your time!

https://camo.githubusercontent.com/880d572e4ff6a55e93be2868f2e55df3cff470bc/687474703a2f2f692e696d6775722e636f6d2f335951654470732e706e67

**Comment by silvestreh** [comment]
I'm almost sure that's [Fira Code](https://github.com/tonsky/FiraCode). Love that font! <3
