### ISSUE TITLE
Javascript multiline header comment incorrect highlighting

### ISSUE THREAD

**Issue by mindpixel-labs** [atom-material/atom-material-syntax#79]
Javascript documentation headers appear to be incorrectly highlighted.

**Reproduction Steps:**

1. Set language/syntax to Javascript
2. Insert/type the following heading comment:
```
/**
 * Heading Comment
 */
```
**Expected behavior:**
![](https://snag.gy/7bL46U.jpg)
Expected behavior is to have the comment portions all muted.

**Observed behavior:**
![](https://snag.gy/8TKsPI.jpg)
Comment syntax is showing some of the asterisks as blue, but should be dark gray/muted

**Atom version:** 1.21.0
**OS and version:** Mac OS 10.12.5 and Windows 10

**Installed packages:**
activate-power-mode@2.5.0
aligner@1.2.4
aligner-javascript@1.3.0
aligner-php@1.2.0
ask-stack@2.2.0
atom-expressionengine@0.4.0
atom-less@0.1.10
atom-material-syntax@1.0.6
atom-material-ui@2.0.4
atom-prettify@0.1.3
atom-typescript@11.0.9
atom-wrap-in-tag@0.6.0
autoprefixer@3.7.1
busy-signal@1.4.3
compile-less@1.0.0
emmet@2.4.3
expand-region@0.3.2
expand-selection-to-quotes@0.11.0
flatwhite-syntax@0.8.1
github-atom-light-syntax@0.5.0
high-street-ui@1.3.0
intentions@1.1.5
language-blade@0.36.0
language-liquid@0.6.0
language-vue-component@0.5.0
linter@2.2.0
linter-ui-default@1.6.10
php-extract-method@0.2.1
platformio-ide-terminal@2.7.0
rgb@1.2.0
set-syntax@0.4.0
sort-lines@0.15.0
sync-settings@0.8.3
tabs-to-spaces@1.0.3
title-case@0.4.0

**Comment by silvestreh** [comment]
I'm unable to reproduce this. Either with Atom's built-in JavaScript syntax or `language-babel`.

<img width="295" alt="captura de pantalla 2017-10-10 a la s 13 01 55" src="https://user-images.githubusercontent.com/1133339/31397060-56af9d5a-adbb-11e7-9263-4dd54897b471.png">

**Comment by mindpixel-labs** [comment]
Very strange. Let me take a look and see. I appreciate your time!

**Comment by mindpixel-labs** [comment]
@silvestreh I tried disabling all packages except this and it still happens on both my Mac and Windows machine. Not sure what's causing it. Quite strange!

**Comment by silvestreh** [comment]
Can't reproduce even with `language-vue-component`

<img width="462" alt="captura de pantalla 2017-10-10 a la s 15 21 07" src="https://user-images.githubusercontent.com/1133339/31403150-aa8c63d2-adce-11e7-97ea-6a44f012ca69.png">

**Comment by silvestreh** [comment]
OK! I managed to reproduce it! I'll work on a fix 😄

**Comment by silvestreh** [comment]
Just pushed a patch! `1.0.7` should be available any minute now.

**Comment by mindpixel-labs** [comment]
@silvestreh You rock, thank you!
