### ISSUE TITLE
Material syntax breaks parentheses matching indicator

### ISSUE THREAD

**Issue by KolorowyAleksander** [atom-material/atom-material-syntax#82]
When the syntax theme is on, proper parentheses matching in one line is not shown, for example:
![atom material same line](https://user-images.githubusercontent.com/11392399/31568592-88f0fd2e-b075-11e7-8a30-4c5c5a7384d4.png)
However, closing parenth in another line shows up properly
(only closing though, I don't know if thats intended):
![atom material diff line](https://user-images.githubusercontent.com/11392399/31568796-bb7a4f24-b076-11e7-8d58-359f0fd541f4.png)
This is clearly a syntax theme issue, same situation after switching to One Dark looks like this:
![one dar](https://user-images.githubusercontent.com/11392399/31568651-df8c5142-b075-11e7-97fe-3a533e056ddd.png) ![one dark 2](https://user-images.githubusercontent.com/11392399/31568654-e270f6d8-b075-11e7-9d68-7f2bb71498b8.png)
Happens on **atom 1.21.1** with no other package than atom-material-syntax and atom-material-ui installed. Seen on both **linux** and **windows**.

**Comment by andremacola** [comment]
same here

**Comment by doryphores** [comment]
#83 should fix this issue

**Comment by doryphores** [comment]
Here's a temporary fix by the way: https://github.com/atom-material/atom-material-syntax/pull/83#issuecomment-351348082
